FROM phusion/baseimage:jammy-1.0.0



ENV http_proxy=http://10.23.4.71:7890
ENV https_proxy=http://10.23.4.71:7890


# 安装所需的工具并清理缓存以减小镜像大小
RUN apt-get update && apt-get install sudo git lazygit fzf curl ripgrep alpine-sdk nodejs npm neovim 


# 复制 addusr.sh 脚本到容器中
COPY addusr.sh /usr/local/bin/addusr.sh
# 运行 addusr.sh 脚本来添加用户
RUN chmod +x /usr/local/bin/addusr.sh && /usr/local/bin/addusr.sh



# 复制本机的 .config/nvim 目录内容到镜像中（需在构建时提供）
COPY --chown={USERNAME}:{USERNAME} nvim /home/{USERNAME}/.config/nvim
RUN chmod -R 777 /home/{USERNAME}/.config


# 设置默认用户
USER {USERNAME}

RUN nvim  --headless "+Lazy! sync " +qa
RUN nvim "+Lazy! install" +MasonToolsInstallSync +q!


WORKDIR /home/{USERNAME}

# 当完成后,清除APT.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
