# 使用 Alpine 的稳定版本作为基础镜像
FROM alpine:edge
# FROM continuumio/miniconda3:22.11.1-alpine

ENV http_proxy=http://10.23.4.71:7890
ENV https_proxy=http://10.23.4.71:7890


# 安装所需的工具并清理缓存以减小镜像大小
RUN apk add --no-cache sudo git lazygit fzf curl ripgrep alpine-sdk nodejs npm neovim python3 py3-pip


# 复制 addusr.sh 脚本到容器中
COPY addusr.sh /usr/local/bin/addusr.sh
# 运行 addusr.sh 脚本来添加用户
RUN chmod +x /usr/local/bin/addusr.sh && /usr/local/bin/addusr.sh && mkdir /home/{USERNAME}/.config && chmod -R 777 /home/{USERNAME}/.config



# 复制本机的 .config/nvim 目录内容到镜像中（需在构建时提供）
COPY --chown={USERNAME}:{USERNAME} nvim /home/{USERNAME}/.config/nvim


# 设置默认用户
USER {USERNAME}

RUN  nvim  --headless "+Lazy! sync " +qa &&  nvim "+Lazy! install" +MasonToolsInstallSync +q!


WORKDIR /home/{USERNAME}
# 设置默认命令为启动 Neovim
# CMD ["nvim"]
